package com.javaelinux.sistemaestoque.model;
// Generated 27/06/2016 23:02:07 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Unidade generated by hbm2java
 */
@Entity
@Table(name = "unidade", catalog = "sistemaestoque")
public class Unidade implements java.io.Serializable {

	private static final long serialVersionUID = -7571809956921261992L;
	private Integer id;
	private String descricao;
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Unidade() {
	}

	public Unidade(String descricao) {
		this.descricao = descricao;
	}
	public Unidade(String descricao, Set<Produto> produtos) {
		this.descricao = descricao;
		this.produtos = produtos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidade")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
