package com.javaelinux.sistemaestoque.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name = "vendedor", catalog = "sistemaestoque")
public class Vendedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2870701530600732900L;
	private Integer id;
	private String nome;
	private String email;
	private String endereco;
	private String cpf;
	private Set<Venda> vendas = new HashSet<Venda>(0);

	public Vendedor() {
	}

	public Vendedor(String nome, String email, String endereco, String cpf,
			Set<Venda> vendas) {
		this.nome = nome;
		this.email = email;
		this.endereco = endereco;
		this.cpf = cpf;
		this.vendas = vendas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "endereco")
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "cpf")
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendedor")
	public Set<Venda> getVendas() {
		return this.vendas;
	}

	public void setVendas(Set<Venda> vendas) {
		this.vendas = vendas;
	}
}
